FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir kafka-python

COPY kafka-producer/producer.py /app/

ENV KAFKA_BROKER=kafka:29092

CMD ["python", "producer.py", "--interval", "5", "--speed", "1"]
